version: '3.8'
services:
  gateway:
    build: gateway/.
    container_name: "shareit-gateway"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/.
    container_name: "shareit-server"
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitdocker

  db:
    image: "postgres:13"
    container_name: "shareit-db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareitdocker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  db:
