CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    CONSTRAINT name_not_blank CHECK (name IS NOT NULL AND name <> ''),
    CONSTRAINT email_not_blank CHECK (email IS NOT NULL AND email <> ''),
    CONSTRAINT email_unique UNIQUE (email)
);