CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100),
    email VARCHAR(100),
    CONSTRAINT user_name_not_blank CHECK (name IS NOT NULL AND name <> ''),
    CONSTRAINT user_email_not_blank CHECK (email IS NOT NULL AND email <> ''),
    CONSTRAINT user_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS users_index ON users (id, email);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    description VARCHAR(1000),
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    available   BOOLEAN,
    CONSTRAINT item_name_not_blank CHECK (name IS NOT NULL AND name <> ''),
    CONSTRAINT item_description_not_blank CHECK (description IS NOT NULL AND description <> ''),
    CONSTRAINT item_owner_id_not_null CHECK (owner_id IS NOT NULL),
    CONSTRAINT item_available_not_null CHECK (available IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS items_index ON items (id, name, description, owner_id);
