CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100),
    email VARCHAR(100),
    CONSTRAINT user_name_not_empty CHECK (name IS NOT NULL AND name <> ''),
    CONSTRAINT user_email_not_empty CHECK (email IS NOT NULL AND email <> ''),
    CONSTRAINT user_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS users_indexes ON users (email);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR,
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT description_is_not_empty CHECK (description IS NOT NULL AND description <> ''),
    CONSTRAINT created_is_not_null CHECK (created IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS item_requests_indexes ON item_requests (description, requester_id);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    description VARCHAR(1000),
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    available   BOOLEAN,
    request_id  BIGINT REFERENCES item_requests (id) ON DELETE CASCADE,
    CONSTRAINT item_name_not_empty CHECK (name IS NOT NULL AND name <> ''),
    CONSTRAINT item_description_not_empty CHECK (description IS NOT NULL AND description <> ''),
    CONSTRAINT item_owner_id_not_null CHECK (owner_id IS NOT NULL),
    CONSTRAINT item_available_not_null CHECK (available IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS items_indexes ON items (name, description, owner_id);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status     VARCHAR(35),
    CONSTRAINT start_date_not_null CHECK (start_date IS NOT NULL),
    CONSTRAINT end_date_not_null CHECK (end_date IS NOT NULL),
    CONSTRAINT end_is_after_start CHECK (end_date > start_date),
    CONSTRAINT status_not_null CHECK (status IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS bookings_indexes ON bookings (booker_id);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      TEXT,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT text_is_not_empty CHECK (text IS NOT NULL AND text <> ''),
    CONSTRAINT created_is_not_null CHECK (created IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS comments_indexes ON comments (item_id, author_id);

CREATE TABLE IF NOT EXISTS item_requests_responses
(
    responses_id    BIGINT REFERENCES items (id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES item_requests (id) ON DELETE CASCADE,
    CONSTRAINT item_requests_responses_pk PRIMARY KEY (responses_id, request_id)
);
